from typing import Protocol, Dict
import pandas as pd
class PriceProvider(Protocol):
    def quote(self, ticker: str) -> Dict: ...
    def history(self, ticker: str, period: str = "1mo", interval: str = "1d") -> pd.DataFrame: ...
