# Streamlit Cloud Secrets Configuration
# This file should be created in your Streamlit Cloud dashboard under "Secrets"

# Default password hash for "echo2024" - you can change this
password_hash = "c3499c2729730a7f807efb8676a92dcb6f8a3f8f0675b84d7f3142c3c7"

# You can generate a new hash for a custom password using:
# python -c "import hashlib; print(hashlib.sha256('your_password'.encode()).hexdigest())"
